<?php

namespace Tiltshift\Algoritmeregister;

use AlgoritmeInfo;

class Algoritmeregister
{

    private $_storageDir;

    public function __construct($storageDir)
    {
        $this->_storageDir = $storageDir;
    }

    public function getIndex()
    {
        $items = [];
        if (($fp = fopen($this->_storageDir . "index.csv", "r")) !== FALSE) {
            $keys = fgetcsv($fp, 1000, ',');
            while (($values = fgetcsv($fp, 1000, ',')) !== false) {
                $items[] = array_combine($keys, $values);
            }
            fclose($fp);
        }
        return $items;
    }

    public function create()
    {
        $metadata = json_decode(file_get_contents(__DIR__ . "/../data/algoritmeregister-metadata-standaard--autogenerated.json"), true);
        $algoritmeInfo = new AlgoritmeInfo($metadata);
        return $algoritmeInfo;
    }

    public function store($algoritmeInfo)
    {
        file_put_contents(__DIR__ . "/../storage/{$algoritmeInfo->getUuid()}." . md5($algoritmeInfo->getUuid()) . ".json", json_encode($algoritmeInfo->getIndexed()));
    }

    public function storeIndex($uuid, $organisatie, $afdeling, $naam, $type, $status, $herziening, $contact, $hash)
    {
        $txt = "\"{$uuid}\",\"{$organisatie}\",\"{$afdeling}\",\"{$naam}\",\"{$type}\",\"{$status}\",\"{$herziening}\",\"{$contact}\",\"{$hash}\"";
        $myfile = file_put_contents($this->_storageDir . "index.csv", $txt.PHP_EOL, FILE_APPEND);
    }

}